export const QUESTION_BANK = {
  Sports: [
    {id:"sp1",q:"Which NBA team has won the most championships in history?",options:["Los Angeles Lakers","Boston Celtics","Chicago Bulls","Golden State Warriors"],answer:1,difficulty:"medium"},
    {id:"sp2",q:"In what year did the Chicago Bulls complete their second NBA three-peat?",options:["1994","1996","1998","2000"],answer:2,difficulty:"hard"},
    {id:"sp3",q:"Which country has won the most FIFA World Cup titles?",options:["Germany","Argentina","Italy","Brazil"],answer:3,difficulty:"easy"},
    {id:"sp4",q:"Before moving to Indianapolis, where were the Colts originally located?",options:["Cleveland","Baltimore","Houston","Memphis"],answer:1,difficulty:"medium"},
    {id:"sp5",q:"Which team won Super Bowl LVIII at the end of the 2023 NFL season?",options:["San Francisco 49ers","Baltimore Ravens","Kansas City Chiefs","Detroit Lions"],answer:2,difficulty:"medium"},
    {id:"sp6",q:"Which tennis player has won the most Grand Slam singles titles in the men's game?",options:["Roger Federer","Rafael Nadal","Novak Djokovic","Pete Sampras"],answer:2,difficulty:"medium"},
    {id:"sp7",q:"How many players are on an ice hockey team on the ice at one time?",options:["5","6","7","4"],answer:1,difficulty:"easy"},
    {id:"sp8",q:"Which athlete famously said I am the greatest?",options:["Pele","Michael Jordan","Muhammad Ali","Jim Brown"],answer:2,difficulty:"easy"},
    {id:"sp9",q:"In what city were the 1996 Summer Olympics held?",options:["Barcelona","Seoul","Atlanta","Sydney"],answer:2,difficulty:"medium"},
    {id:"sp10",q:"Which MLB team ended a 108-year championship drought in the 2016 World Series?",options:["Boston Red Sox","Chicago Cubs","Cleveland Indians","Los Angeles Dodgers"],answer:1,difficulty:"medium"},
    {id:"sp11",q:"What is the maximum score possible in a single game of bowling?",options:["270","290","300","310"],answer:2,difficulty:"easy"},
    {id:"sp12",q:"Which country won the first-ever FIFA World Cup in 1930?",options:["Brazil","Argentina","Uruguay","Italy"],answer:2,difficulty:"hard"},
    {id:"sp13",q:"How long is a standard marathon race?",options:["24.2 miles","26.2 miles","28.2 miles","25 miles"],answer:1,difficulty:"easy"},
    {id:"sp14",q:"Which golfer holds the record for the most major championship wins?",options:["Tiger Woods","Jack Nicklaus","Arnold Palmer","Phil Mickelson"],answer:1,difficulty:"medium"},
    {id:"sp15",q:"In American football, how many points is a safety worth?",options:["1","2","3","6"],answer:1,difficulty:"medium"},
    {id:"sp16",q:"Which country has won the most Olympic gold medals overall?",options:["Soviet Union","China","Great Britain","United States"],answer:3,difficulty:"medium"},
    {id:"sp17",q:"In what sport would you perform a Fosbury Flop?",options:["Gymnastics","Pole Vault","High Jump","Long Jump"],answer:2,difficulty:"medium"},
    {id:"sp18",q:"How many Grand Slam tournaments are there in tennis?",options:["2","3","4","5"],answer:2,difficulty:"easy"},
    {id:"sp19",q:"What sport is played at Wimbledon?",options:["Cricket","Polo","Squash","Tennis"],answer:3,difficulty:"easy"},
    {id:"sp20",q:"How many players are on a basketball team on the court at one time?",options:["4","5","6","7"],answer:1,difficulty:"easy"},
    {id:"sp21",q:"Which NFL team has won the most Super Bowls?",options:["New England Patriots","Dallas Cowboys","San Francisco 49ers","Pittsburgh Steelers"],answer:3,difficulty:"hard"},
    {id:"sp22",q:"In what year were the first modern Olympic Games held?",options:["1888","1896","1904","1912"],answer:1,difficulty:"medium"},
    {id:"sp23",q:"Which sport uses a puck?",options:["Field Hockey","Ice Hockey","Lacrosse","Polo"],answer:1,difficulty:"easy"},
    {id:"sp24",q:"Who holds the NFL record for most career rushing yards?",options:["Barry Sanders","Emmitt Smith","Walter Payton","Eric Dickerson"],answer:1,difficulty:"hard"},
    {id:"sp25",q:"In baseball, how many strikes does it take to strike out a batter?",options:["2","3","4","5"],answer:1,difficulty:"easy"},
    {id:"sp26",q:"Which country invented the sport of rugby?",options:["Australia","Scotland","Ireland","England"],answer:3,difficulty:"medium"},
    {id:"sp27",q:"In what year did Tiger Woods win his first Masters Tournament?",options:["1995","1996","1997","1999"],answer:2,difficulty:"medium"},
    {id:"sp28",q:"How many points is a touchdown worth in American football?",options:["3","4","6","7"],answer:2,difficulty:"easy"},
    {id:"sp29",q:"Which swimmer has won the most Olympic gold medals ever?",options:["Mark Spitz","Ian Thorpe","Ryan Lochte","Michael Phelps"],answer:3,difficulty:"easy"},
    {id:"sp30",q:"In soccer, how many players are on each team on the field?",options:["9","10","11","12"],answer:2,difficulty:"easy"},
    {id:"sp31",q:"Which F1 driver has won the most World Championship titles?",options:["Ayrton Senna","Michael Schumacher","Lewis Hamilton","Sebastian Vettel"],answer:2,difficulty:"medium"},
    {id:"sp32",q:"How long is an Olympic swimming pool in meters?",options:["25","50","75","100"],answer:1,difficulty:"easy"},
    {id:"sp33",q:"Which team did LeBron James win his first NBA championship with?",options:["Cleveland Cavaliers","Los Angeles Lakers","Miami Heat","Chicago Bulls"],answer:2,difficulty:"medium"},
    {id:"sp34",q:"In cricket, how many runs is a century?",options:["50","75","100","150"],answer:2,difficulty:"easy"},
    {id:"sp35",q:"Which country has won the most Rugby World Cup titles?",options:["Australia","South Africa","England","New Zealand"],answer:3,difficulty:"medium"},
    {id:"sp36",q:"Who was the first gymnast to score a perfect 10 in Olympic competition?",options:["Simone Biles","Mary Lou Retton","Larisa Latynina","Nadia Comaneci"],answer:3,difficulty:"medium"},
    {id:"sp37",q:"In golf, what is the term for two strokes under par on a hole?",options:["Birdie","Eagle","Albatross","Bogey"],answer:1,difficulty:"medium"},
    {id:"sp38",q:"How many events are in a decathlon?",options:["8","9","10","12"],answer:2,difficulty:"easy"},
    {id:"sp39",q:"Which stadium is home to the New York Yankees?",options:["Citi Field","Fenway Park","Yankee Stadium","Camden Yards"],answer:2,difficulty:"easy"},
    {id:"sp40",q:"What sport does Ronda Rousey compete in?",options:["Boxing","Judo and MMA","Wrestling","Kickboxing"],answer:1,difficulty:"medium"},
    {id:"sp41",q:"Which city hosted the first Super Bowl?",options:["Miami","New Orleans","Los Angeles","Dallas"],answer:2,difficulty:"hard"},
    {id:"sp42",q:"What is the diameter of a basketball hoop in inches?",options:["14","16","18","20"],answer:2,difficulty:"hard"},
    {id:"sp43",q:"In what year did Michael Jordan first retire from basketball?",options:["1991","1993","1995","1997"],answer:1,difficulty:"medium"},
    {id:"sp44",q:"What sport is known as The Beautiful Game?",options:["Basketball","Soccer","Tennis","Baseball"],answer:1,difficulty:"easy"},
    {id:"sp45",q:"Which horse race is known as The Greatest Two Minutes in Sports?",options:["Preakness Stakes","Belmont Stakes","Kentucky Derby","Breeders Cup"],answer:2,difficulty:"medium"},
    {id:"sp46",q:"Which country won the most medals at the 2020 Tokyo Olympics?",options:["China","Russia","Japan","United States"],answer:3,difficulty:"medium"},
    {id:"sp47",q:"Which country has won the most Davis Cup titles in tennis?",options:["Sweden","Australia","Spain","United States"],answer:3,difficulty:"hard"},
    {id:"sp48",q:"What is the highest belt color in traditional judo?",options:["Brown","Red","Black","White"],answer:1,difficulty:"medium"},
    {id:"sp49",q:"What is the only country to have competed in every Summer Olympics since 1896?",options:["France","United Kingdom","Greece","Australia"],answer:2,difficulty:"hard"},
    {id:"sp50",q:"In what year did the first Boston Marathon take place?",options:["1887","1897","1907","1917"],answer:1,difficulty:"hard"},
  ],
  History: [
    {id:"hi1",q:"In what year did World War II end?",options:["1943","1944","1945","1946"],answer:2,difficulty:"easy"},
    {id:"hi2",q:"Who was the first President of the United States?",options:["John Adams","Thomas Jefferson","Benjamin Franklin","George Washington"],answer:3,difficulty:"easy"},
    {id:"hi3",q:"The Berlin Wall fell in which year?",options:["1987","1988","1989","1991"],answer:2,difficulty:"medium"},
    {id:"hi4",q:"Which ancient wonder was located in Alexandria, Egypt?",options:["The Colossus of Rhodes","The Lighthouse of Alexandria","The Hanging Gardens","The Temple of Artemis"],answer:1,difficulty:"hard"},
    {id:"hi5",q:"The Magna Carta was signed in which year?",options:["1066","1215","1348","1492"],answer:1,difficulty:"medium"},
    {id:"hi6",q:"Who was the pharaoh during the construction of the Great Pyramid of Giza?",options:["Ramesses II","Tutankhamun","Khufu","Cleopatra"],answer:2,difficulty:"hard"},
    {id:"hi7",q:"The United States declared independence from Britain in what year?",options:["1774","1775","1776","1783"],answer:2,difficulty:"easy"},
    {id:"hi8",q:"Which empire was ruled by Genghis Khan?",options:["Ottoman Empire","Mongol Empire","Roman Empire","Persian Empire"],answer:1,difficulty:"easy"},
    {id:"hi9",q:"The French Revolution began in which year?",options:["1776","1783","1789","1799"],answer:2,difficulty:"medium"},
    {id:"hi10",q:"Who was the first woman to win a Nobel Prize?",options:["Rosalind Franklin","Marie Curie","Ada Lovelace","Florence Nightingale"],answer:1,difficulty:"medium"},
    {id:"hi11",q:"The Roman Colosseum was completed in approximately which year?",options:["72 BC","80 AD","120 AD","250 AD"],answer:1,difficulty:"hard"},
    {id:"hi12",q:"Which country was the first to give women the right to vote nationally?",options:["United States","United Kingdom","New Zealand","Sweden"],answer:2,difficulty:"hard"},
    {id:"hi13",q:"The first moon landing took place in what year?",options:["1967","1968","1969","1970"],answer:2,difficulty:"easy"},
    {id:"hi14",q:"Which battle is considered the turning point of the American Civil War?",options:["Bull Run","Antietam","Gettysburg","Vicksburg"],answer:2,difficulty:"medium"},
    {id:"hi15",q:"In what year did the Titanic sink?",options:["1910","1911","1912","1913"],answer:2,difficulty:"easy"},
    {id:"hi16",q:"Which ancient civilization built Machu Picchu?",options:["Aztec","Maya","Inca","Olmec"],answer:2,difficulty:"medium"},
    {id:"hi17",q:"Who was the last pharaoh of ancient Egypt?",options:["Nefertiti","Cleopatra VII","Hatshepsut","Ramesses III"],answer:1,difficulty:"medium"},
    {id:"hi18",q:"The Hundred Years War was fought between which two countries?",options:["Spain and Portugal","England and France","Germany and Austria","Italy and Greece"],answer:1,difficulty:"medium"},
    {id:"hi19",q:"Who wrote the Declaration of Independence?",options:["Benjamin Franklin","John Adams","Alexander Hamilton","Thomas Jefferson"],answer:3,difficulty:"easy"},
    {id:"hi20",q:"In what year did the Soviet Union dissolve?",options:["1989","1990","1991","1993"],answer:2,difficulty:"medium"},
    {id:"hi21",q:"Which empire was the largest in history by land area?",options:["Roman Empire","British Empire","Mongol Empire","Ottoman Empire"],answer:1,difficulty:"hard"},
    {id:"hi22",q:"Who commanded the Allied forces on D-Day?",options:["General Patton","General Bradley","General MacArthur","Dwight D. Eisenhower"],answer:3,difficulty:"medium"},
    {id:"hi23",q:"The Black Death primarily struck Europe in which century?",options:["12th","13th","14th","15th"],answer:2,difficulty:"medium"},
    {id:"hi24",q:"Which US president issued the Emancipation Proclamation?",options:["Ulysses Grant","Andrew Johnson","Abraham Lincoln","James Buchanan"],answer:2,difficulty:"easy"},
    {id:"hi25",q:"In what year did Christopher Columbus first reach the Americas?",options:["1488","1490","1492","1498"],answer:2,difficulty:"easy"},
    {id:"hi26",q:"Which country was the first to develop nuclear weapons?",options:["Soviet Union","Germany","United Kingdom","United States"],answer:3,difficulty:"easy"},
    {id:"hi27",q:"The Great Wall of China was primarily built during which dynasty?",options:["Han","Tang","Ming","Qin"],answer:2,difficulty:"hard"},
    {id:"hi28",q:"Who was the first Roman emperor?",options:["Julius Caesar","Nero","Augustus","Caligula"],answer:2,difficulty:"medium"},
    {id:"hi29",q:"In what year did World War I begin?",options:["1912","1913","1914","1916"],answer:2,difficulty:"easy"},
    {id:"hi30",q:"Which revolution introduced liberty equality and fraternity as ideals?",options:["American Revolution","Russian Revolution","French Revolution","Industrial Revolution"],answer:2,difficulty:"easy"},
    {id:"hi31",q:"The Aztec empire was conquered by which European explorer?",options:["Francisco Pizarro","Vasco da Gama","Hernan Cortes","Ferdinand Magellan"],answer:2,difficulty:"medium"},
    {id:"hi32",q:"Which king signed the Magna Carta?",options:["King Richard I","King John","King Henry II","King Edward I"],answer:1,difficulty:"medium"},
    {id:"hi33",q:"The Cuban Missile Crisis occurred in what year?",options:["1960","1961","1962","1964"],answer:2,difficulty:"medium"},
    {id:"hi34",q:"Who was the leader of the Soviet Union during most of World War II?",options:["Lenin","Khrushchev","Brezhnev","Stalin"],answer:3,difficulty:"easy"},
    {id:"hi35",q:"Which year did the Korean War end?",options:["1950","1951","1953","1955"],answer:2,difficulty:"medium"},
    {id:"hi36",q:"Who was the first female Prime Minister of the United Kingdom?",options:["Margaret Thatcher","Theresa May","Hillary Clinton","Indira Gandhi"],answer:0,difficulty:"easy"},
    {id:"hi37",q:"In what year was the United Nations founded?",options:["1943","1944","1945","1947"],answer:2,difficulty:"medium"},
    {id:"hi38",q:"The Renaissance began in which country?",options:["France","Spain","Germany","Italy"],answer:3,difficulty:"medium"},
    {id:"hi39",q:"Which US president was assassinated in 1963?",options:["Dwight Eisenhower","Lyndon Johnson","John F. Kennedy","Richard Nixon"],answer:2,difficulty:"easy"},
    {id:"hi40",q:"The Battle of Waterloo took place in which year?",options:["1812","1813","1814","1815"],answer:3,difficulty:"medium"},
    {id:"hi41",q:"Which ancient library was the greatest repository of knowledge in antiquity?",options:["Library of Athens","Library of Baghdad","Library of Alexandria","Library of Constantinople"],answer:2,difficulty:"medium"},
    {id:"hi42",q:"Who led the Cuban Revolution?",options:["Che Guevara","Raul Castro","Fulgencio Batista","Fidel Castro"],answer:3,difficulty:"easy"},
    {id:"hi43",q:"In what year did the United States enter World War II?",options:["1939","1940","1941","1942"],answer:2,difficulty:"easy"},
    {id:"hi44",q:"Which explorer is credited as the first to circumnavigate the globe?",options:["Christopher Columbus","Vasco da Gama","Ferdinand Magellan","James Cook"],answer:2,difficulty:"medium"},
    {id:"hi45",q:"The Opium Wars were fought between China and which country?",options:["France","United States","Russia","Britain"],answer:3,difficulty:"hard"},
    {id:"hi46",q:"Who was the first person to walk on the moon?",options:["Buzz Aldrin","Yuri Gagarin","Neil Armstrong","Alan Shepard"],answer:2,difficulty:"easy"},
    {id:"hi47",q:"In what year did apartheid officially end in South Africa?",options:["1990","1991","1993","1994"],answer:3,difficulty:"medium"},
    {id:"hi48",q:"Which dynasty built the Forbidden City in Beijing?",options:["Han","Song","Ming","Tang"],answer:2,difficulty:"hard"},
    {id:"hi49",q:"In what year did the Berlin Wall begin construction?",options:["1958","1959","1961","1963"],answer:2,difficulty:"hard"},
    {id:"hi50",q:"Which country had the first written constitution in the modern era?",options:["France","United Kingdom","United States","Poland"],answer:2,difficulty:"hard"},
  ],
  "Pop Culture": [
    {id:"pc1",q:"Which movie holds the all-time worldwide box office record as of 2023?",options:["Titanic","Avengers Endgame","Avatar","The Lion King"],answer:2,difficulty:"medium"},
    {id:"pc2",q:"In The Office US what is the name of the paper company?",options:["Dunder Mifflin","Wernham Hogg","Initech","Prestige Worldwide"],answer:0,difficulty:"easy"},
    {id:"pc3",q:"Which actress played Katniss Everdeen in The Hunger Games?",options:["Shailene Woodley","Emma Stone","Jennifer Lawrence","Kristen Stewart"],answer:2,difficulty:"easy"},
    {id:"pc4",q:"What year did the first iPhone launch?",options:["2005","2006","2007","2008"],answer:2,difficulty:"medium"},
    {id:"pc5",q:"Which TV show features the fictional city of Pawnee Indiana?",options:["30 Rock","Parks and Recreation","Community","Brooklyn Nine-Nine"],answer:1,difficulty:"medium"},
    {id:"pc6",q:"In Breaking Bad what is Walter Whites alter ego called?",options:["The Cook","Heisenberg","El Profesor","Blue Sky"],answer:1,difficulty:"easy"},
    {id:"pc7",q:"Which social media platform was originally called Twttr?",options:["Instagram","Snapchat","Twitter","Facebook"],answer:2,difficulty:"medium"},
    {id:"pc8",q:"What is the name of the coffee shop in Friends?",options:["Central Perk","The Grind","Java Joes","The Percolator"],answer:0,difficulty:"easy"},
    {id:"pc9",q:"Which Marvel superhero is known as the Merc with a Mouth?",options:["Spider-Man","Deadpool","Wolverine","Punisher"],answer:1,difficulty:"easy"},
    {id:"pc10",q:"What year did the final episode of Game of Thrones air?",options:["2017","2018","2019","2020"],answer:2,difficulty:"medium"},
    {id:"pc11",q:"Who directed the Jurassic Park film series?",options:["James Cameron","Steven Spielberg","George Lucas","Ron Howard"],answer:1,difficulty:"easy"},
    {id:"pc12",q:"What is the best-selling video game of all time?",options:["Tetris","Minecraft","GTA V","Wii Sports"],answer:1,difficulty:"medium"},
    {id:"pc13",q:"What is the name of Tony Starks AI assistant in Iron Man?",options:["ARIA","SARA","JARVIS","AXIOM"],answer:2,difficulty:"easy"},
    {id:"pc14",q:"Which actress plays Meredith Grey in Greys Anatomy?",options:["Sandra Oh","Kate Walsh","Chandra Wilson","Ellen Pompeo"],answer:3,difficulty:"easy"},
    {id:"pc15",q:"In which fictional town does Stranger Things take place?",options:["Hawkins","Derry","Castle Rock","Riverdale"],answer:0,difficulty:"easy"},
    {id:"pc16",q:"What streaming service originally aired House of Cards US?",options:["Hulu","HBO","Amazon Prime","Netflix"],answer:3,difficulty:"easy"},
    {id:"pc17",q:"Which animated film features the song Let It Go?",options:["Brave","Tangled","Frozen","Moana"],answer:2,difficulty:"easy"},
    {id:"pc18",q:"Who voices Woody in the Toy Story franchise?",options:["Tom Hanks","Tim Allen","Billy Crystal","John Goodman"],answer:0,difficulty:"easy"},
    {id:"pc19",q:"Which actor played Iron Man in the MCU?",options:["Chris Evans","Chris Hemsworth","Robert Downey Jr","Mark Ruffalo"],answer:2,difficulty:"easy"},
    {id:"pc20",q:"Which pop star is known as The Material Girl?",options:["Whitney Houston","Madonna","Cyndi Lauper","Cher"],answer:1,difficulty:"easy"},
    {id:"pc21",q:"In what year was YouTube founded?",options:["2003","2004","2005","2006"],answer:2,difficulty:"medium"},
    {id:"pc22",q:"Who played the Joker in The Dark Knight 2008?",options:["Jared Leto","Joaquin Phoenix","Jack Nicholson","Heath Ledger"],answer:3,difficulty:"easy"},
    {id:"pc23",q:"Which network airs Saturday Night Live?",options:["ABC","CBS","NBC","Fox"],answer:2,difficulty:"easy"},
    {id:"pc24",q:"Who wrote the Harry Potter series?",options:["Stephenie Meyer","Suzanne Collins","J.K. Rowling","Philip Pullman"],answer:2,difficulty:"easy"},
    {id:"pc25",q:"Which movie features the line You cant handle the truth?",options:["The Firm","Philadelphia","A Few Good Men","Born on the Fourth of July"],answer:2,difficulty:"medium"},
    {id:"pc26",q:"Which actress played Elle Woods in Legally Blonde?",options:["Reese Witherspoon","Cameron Diaz","Renee Zellweger","Kate Hudson"],answer:0,difficulty:"easy"},
    {id:"pc27",q:"The fictional Hogwarts school is located in which country?",options:["England","Scotland","Ireland","Wales"],answer:1,difficulty:"medium"},
    {id:"pc28",q:"In The Lion King what is the name of Simbas father?",options:["Rafiki","Scar","Zazu","Mufasa"],answer:3,difficulty:"easy"},
    {id:"pc29",q:"Which director is known for Pulp Fiction and Kill Bill?",options:["Martin Scorsese","Quentin Tarantino","David Fincher","Wes Anderson"],answer:1,difficulty:"easy"},
    {id:"pc30",q:"What is the name of the fictional country in Black Panther?",options:["Genosha","Latveria","Wakanda","Sokovia"],answer:2,difficulty:"easy"},
    {id:"pc31",q:"Who played Forrest Gump in the 1994 film?",options:["Kevin Costner","John Travolta","Tom Hanks","Mel Gibson"],answer:2,difficulty:"easy"},
    {id:"pc32",q:"In what city is Cheers set?",options:["New York","Chicago","Boston","Philadelphia"],answer:2,difficulty:"easy"},
    {id:"pc33",q:"Which actor played Jack Sparrow in Pirates of the Caribbean?",options:["Orlando Bloom","Keira Knightley","Geoffrey Rush","Johnny Depp"],answer:3,difficulty:"easy"},
    {id:"pc34",q:"What is the name of Andys neighbor in Toy Story?",options:["Sid","Phil","Todd","Mike"],answer:0,difficulty:"medium"},
    {id:"pc35",q:"Who played Neo in The Matrix?",options:["Brad Pitt","Tom Cruise","Keanu Reeves","Will Smith"],answer:2,difficulty:"easy"},
    {id:"pc36",q:"What is the subtitle of the second Avengers film?",options:["Civil War","Age of Ultron","Infinity War","Endgame"],answer:1,difficulty:"easy"},
    {id:"pc37",q:"Which comedian created and starred in Seinfeld?",options:["Larry David","Jerry Seinfeld","Ray Romano","Louis C.K."],answer:1,difficulty:"easy"},
    {id:"pc38",q:"In The Simpsons what is the name of the town they live in?",options:["Shelbyville","Capital City","Springfield","Ogdenville"],answer:2,difficulty:"easy"},
    {id:"pc39",q:"Which actor plays Sherlock Holmes in the BBC series Sherlock?",options:["Ian McKellen","Martin Freeman","Benedict Cumberbatch","David Tennant"],answer:2,difficulty:"easy"},
    {id:"pc40",q:"What movie features the fictional Nakatomi Plaza?",options:["Speed","Lethal Weapon","Beverly Hills Cop","Die Hard"],answer:3,difficulty:"medium"},
    {id:"pc41",q:"Which show has the most Emmy Awards ever?",options:["Game of Thrones","The Simpsons","Saturday Night Live","Frasier"],answer:0,difficulty:"hard"},
    {id:"pc42",q:"Which show is set in the fictional Westeros?",options:["Vikings","Marco Polo","The Last Kingdom","Game of Thrones"],answer:3,difficulty:"easy"},
    {id:"pc43",q:"In what year did Netflix launch its streaming service?",options:["2005","2006","2007","2008"],answer:2,difficulty:"medium"},
    {id:"pc44",q:"Which actress plays the lead in Killing Eve?",options:["Jodie Comer","Sandra Oh","Ruth Wilson","Olivia Colman"],answer:1,difficulty:"medium"},
    {id:"pc45",q:"What is the name of the bar in Its Always Sunny in Philadelphia?",options:["Paddys Pub","Cheers","The Rusty Nail","MacLarens"],answer:0,difficulty:"medium"},
    {id:"pc46",q:"Which show features a chemistry teacher turned drug kingpin?",options:["Narcos","Ozark","Breaking Bad","Dexter"],answer:2,difficulty:"easy"},
    {id:"pc47",q:"How many seasons does the original run of The Sopranos have?",options:["4","5","6","7"],answer:2,difficulty:"hard"},
    {id:"pc48",q:"What is the highest-grossing R-rated movie of all time?",options:["The Matrix","Joker","Deadpool","It"],answer:1,difficulty:"hard"},
    {id:"pc49",q:"Which show popularized the phrase Winter is Coming?",options:["Vikings","The Last Kingdom","Outlander","Game of Thrones"],answer:3,difficulty:"easy"},
    {id:"pc50",q:"What is the name of the fictional high school in Grease?",options:["Bayside High","Rydell High","West Beverly","Shermer High"],answer:1,difficulty:"medium"},
  ],
  "Science & Nature": [
    {id:"sc1",q:"What is the chemical symbol for gold?",options:["Go","Gd","Au","Ag"],answer:2,difficulty:"easy"},
    {id:"sc2",q:"How many chromosomes do humans typically have?",options:["23","44","46","48"],answer:2,difficulty:"medium"},
    {id:"sc3",q:"What is the speed of light in a vacuum approximately?",options:["186000 miles per second","300000 km per second","Both A and B are correct","150000 km per second"],answer:2,difficulty:"hard"},
    {id:"sc4",q:"Which planet in our solar system has the most moons?",options:["Jupiter","Saturn","Uranus","Neptune"],answer:1,difficulty:"medium"},
    {id:"sc5",q:"DNA stands for what?",options:["Deoxyribonucleic Acid","Dioxyribose Nucleic Acid","Dual Nucleotide Amino Acid","Dynamic Nucleic Arrangement"],answer:0,difficulty:"easy"},
    {id:"sc6",q:"What is the hardest natural substance on Earth?",options:["Titanium","Quartz","Diamond","Tungsten"],answer:2,difficulty:"easy"},
    {id:"sc7",q:"How many bones are in the adult human body?",options:["196","206","216","226"],answer:1,difficulty:"medium"},
    {id:"sc8",q:"What gas do plants absorb during photosynthesis?",options:["Oxygen","Nitrogen","Carbon Dioxide","Hydrogen"],answer:2,difficulty:"easy"},
    {id:"sc9",q:"What is the most abundant gas in Earths atmosphere?",options:["Oxygen","Carbon Dioxide","Argon","Nitrogen"],answer:3,difficulty:"medium"},
    {id:"sc10",q:"Which scientist developed the theory of general relativity?",options:["Isaac Newton","Albert Einstein","Niels Bohr","Max Planck"],answer:1,difficulty:"easy"},
    {id:"sc11",q:"What is the atomic number of carbon?",options:["4","6","8","12"],answer:1,difficulty:"medium"},
    {id:"sc12",q:"How long does it take light from the Sun to reach Earth?",options:["4 minutes","8 minutes","12 minutes","16 minutes"],answer:1,difficulty:"medium"},
    {id:"sc13",q:"What is the process by which cells divide?",options:["Mitosis","Osmosis","Meiosis","Photosynthesis"],answer:0,difficulty:"medium"},
    {id:"sc14",q:"Which element is liquid at room temperature besides mercury?",options:["Gallium","Bromine","Cesium","Francium"],answer:1,difficulty:"hard"},
    {id:"sc15",q:"What is the powerhouse of the cell?",options:["Nucleus","Ribosome","Mitochondria","Golgi Apparatus"],answer:2,difficulty:"easy"},
    {id:"sc16",q:"What planet is known as the Red Planet?",options:["Venus","Jupiter","Mars","Saturn"],answer:2,difficulty:"easy"},
    {id:"sc17",q:"How many elements are on the periodic table as of 2024?",options:["108","112","118","124"],answer:2,difficulty:"medium"},
    {id:"sc18",q:"What force keeps planets in orbit around the Sun?",options:["Magnetism","Electromagnetism","Nuclear Force","Gravity"],answer:3,difficulty:"easy"},
    {id:"sc19",q:"What is the boiling point of water at sea level in Celsius?",options:["90","95","100","105"],answer:2,difficulty:"easy"},
    {id:"sc20",q:"Which organ produces insulin?",options:["Liver","Kidney","Stomach","Pancreas"],answer:3,difficulty:"medium"},
    {id:"sc21",q:"What is the smallest unit of life?",options:["Atom","Molecule","Cell","Organelle"],answer:2,difficulty:"easy"},
    {id:"sc22",q:"Which gas makes up most of the Sun?",options:["Helium","Carbon","Hydrogen","Oxygen"],answer:2,difficulty:"medium"},
    {id:"sc23",q:"What is the chemical formula for water?",options:["HO","H2O","H3O","H2O2"],answer:1,difficulty:"easy"},
    {id:"sc24",q:"How many chambers does the human heart have?",options:["2","3","4","5"],answer:2,difficulty:"easy"},
    {id:"sc25",q:"What is the nearest star to Earth besides the Sun?",options:["Sirius","Betelgeuse","Proxima Centauri","Vega"],answer:2,difficulty:"medium"},
    {id:"sc26",q:"What type of animal is a Komodo dragon?",options:["Snake","Turtle","Lizard","Crocodilian"],answer:2,difficulty:"easy"},
    {id:"sc27",q:"What is the study of earthquakes called?",options:["Volcanology","Geology","Seismology","Geomorphology"],answer:2,difficulty:"medium"},
    {id:"sc28",q:"Which planet rotates on its side with an axial tilt of about 98 degrees?",options:["Neptune","Saturn","Pluto","Uranus"],answer:3,difficulty:"hard"},
    {id:"sc29",q:"What is the chemical symbol for iron?",options:["Ir","In","Fe","Fr"],answer:2,difficulty:"medium"},
    {id:"sc30",q:"Which blood type is the universal donor?",options:["A+","O-","AB+","B-"],answer:1,difficulty:"medium"},
    {id:"sc31",q:"What is the process by which plants lose water through leaves?",options:["Transpiration","Respiration","Evaporation","Condensation"],answer:0,difficulty:"medium"},
    {id:"sc32",q:"How many planets are in our solar system?",options:["7","8","9","10"],answer:1,difficulty:"easy"},
    {id:"sc33",q:"What is the unit of electrical resistance?",options:["Volt","Watt","Ampere","Ohm"],answer:3,difficulty:"medium"},
    {id:"sc34",q:"What is the most abundant metal in Earths crust?",options:["Iron","Calcium","Aluminum","Silicon"],answer:2,difficulty:"hard"},
    {id:"sc35",q:"What type of bond shares electrons between atoms?",options:["Ionic","Covalent","Hydrogen","Metallic"],answer:1,difficulty:"medium"},
    {id:"sc36",q:"What is the layer of Earth between the crust and core called?",options:["Biosphere","Mantle","Lithosphere","Asthenosphere"],answer:1,difficulty:"medium"},
    {id:"sc37",q:"What phenomenon causes the sky to appear blue?",options:["Reflection","Refraction","Rayleigh Scattering","Diffraction"],answer:2,difficulty:"hard"},
    {id:"sc38",q:"What is the approximate age of the universe?",options:["4.6 billion years","10 billion years","13.8 billion years","20 billion years"],answer:2,difficulty:"medium"},
    {id:"sc39",q:"What particle has a positive charge in an atom?",options:["Electron","Neutron","Proton","Quark"],answer:2,difficulty:"easy"},
    {id:"sc40",q:"Which type of rock is formed from cooled lava?",options:["Sedimentary","Metamorphic","Igneous","Limestone"],answer:2,difficulty:"easy"},
    {id:"sc41",q:"What is the scientific name for the human kneecap?",options:["Fibula","Tibia","Patella","Femur"],answer:2,difficulty:"medium"},
    {id:"sc42",q:"Which planet has a storm known as the Great Red Spot?",options:["Saturn","Uranus","Neptune","Jupiter"],answer:3,difficulty:"easy"},
    {id:"sc43",q:"What law states that force equals mass times acceleration?",options:["Newtons First Law","Newtons Second Law","Newtons Third Law","Keplers Law"],answer:1,difficulty:"medium"},
    {id:"sc44",q:"What is the most common element in the universe?",options:["Oxygen","Carbon","Helium","Hydrogen"],answer:3,difficulty:"medium"},
    {id:"sc45",q:"What type of animal is a salamander?",options:["Reptile","Mammal","Amphibian","Fish"],answer:2,difficulty:"easy"},
    {id:"sc46",q:"What is the speed of sound in air at sea level approximately?",options:["343 m/s","500 m/s","760 m/s","1000 m/s"],answer:0,difficulty:"medium"},
    {id:"sc47",q:"How many chromosomes does a typical human egg cell contain?",options:["23","46","47","92"],answer:0,difficulty:"hard"},
    {id:"sc48",q:"What is the term for an animal that eats only plants?",options:["Carnivore","Herbivore","Omnivore","Insectivore"],answer:1,difficulty:"easy"},
    {id:"sc49",q:"What is the most common element in the human body by mass?",options:["Carbon","Hydrogen","Nitrogen","Oxygen"],answer:3,difficulty:"medium"},
    {id:"sc50",q:"Which vitamin is produced when skin is exposed to sunlight?",options:["Vitamin A","Vitamin C","Vitamin D","Vitamin K"],answer:2,difficulty:"easy"},
  ],
  Geography: [
    {id:"ge1",q:"What is the capital city of Australia?",options:["Sydney","Melbourne","Canberra","Brisbane"],answer:2,difficulty:"medium"},
    {id:"ge2",q:"Which is the longest river in the world?",options:["Amazon","Mississippi","Yangtze","Nile"],answer:3,difficulty:"medium"},
    {id:"ge3",q:"How many countries are in Africa?",options:["48","52","54","58"],answer:2,difficulty:"hard"},
    {id:"ge4",q:"What is the smallest country in the world by area?",options:["Monaco","San Marino","Vatican City","Liechtenstein"],answer:2,difficulty:"medium"},
    {id:"ge5",q:"Which mountain range separates Europe from Asia?",options:["Alps","Caucasus","Ural Mountains","Carpathians"],answer:2,difficulty:"hard"},
    {id:"ge6",q:"What is the largest ocean on Earth?",options:["Atlantic","Indian","Arctic","Pacific"],answer:3,difficulty:"easy"},
    {id:"ge7",q:"Which country has the most natural lakes in the world?",options:["Russia","United States","Canada","Finland"],answer:2,difficulty:"hard"},
    {id:"ge8",q:"What is the capital of Brazil?",options:["Sao Paulo","Rio de Janeiro","Brasilia","Salvador"],answer:2,difficulty:"medium"},
    {id:"ge9",q:"Which desert is the largest in the world?",options:["Sahara","Gobi","Arabian","Antarctic"],answer:3,difficulty:"hard"},
    {id:"ge10",q:"How many time zones does Russia span?",options:["9","10","11","13"],answer:2,difficulty:"hard"},
    {id:"ge11",q:"What is the tallest mountain in the world?",options:["K2","Kangchenjunga","Mount Everest","Makalu"],answer:2,difficulty:"easy"},
    {id:"ge12",q:"Which country is both an island and a continent?",options:["New Zealand","Greenland","Australia","Madagascar"],answer:2,difficulty:"easy"},
    {id:"ge13",q:"What is the capital of Canada?",options:["Toronto","Vancouver","Montreal","Ottawa"],answer:3,difficulty:"medium"},
    {id:"ge14",q:"The Amazon Rainforest is primarily in which country?",options:["Colombia","Peru","Venezuela","Brazil"],answer:3,difficulty:"easy"},
    {id:"ge15",q:"Which US state is the largest by area?",options:["Texas","California","Montana","Alaska"],answer:3,difficulty:"easy"},
    {id:"ge16",q:"What is the capital of Japan?",options:["Osaka","Kyoto","Hiroshima","Tokyo"],answer:3,difficulty:"easy"},
    {id:"ge17",q:"Which country has the largest population in the world?",options:["United States","China","India","Indonesia"],answer:2,difficulty:"easy"},
    {id:"ge18",q:"What is the longest mountain range in the world?",options:["Rocky Mountains","Himalayas","Andes","Alps"],answer:2,difficulty:"medium"},
    {id:"ge19",q:"Which African country is the most populous?",options:["South Africa","Ethiopia","Egypt","Nigeria"],answer:3,difficulty:"medium"},
    {id:"ge20",q:"What is the capital of Argentina?",options:["Montevideo","Lima","Santiago","Buenos Aires"],answer:3,difficulty:"medium"},
    {id:"ge21",q:"Which body of water is the saltiest in the world?",options:["Red Sea","Caspian Sea","Dead Sea","Mediterranean Sea"],answer:2,difficulty:"medium"},
    {id:"ge22",q:"What is the capital of South Korea?",options:["Busan","Seoul","Incheon","Pyongyang"],answer:1,difficulty:"easy"},
    {id:"ge23",q:"Which country has the most coastline?",options:["Russia","Australia","Norway","Canada"],answer:3,difficulty:"hard"},
    {id:"ge24",q:"What is the largest country by land area?",options:["Canada","China","United States","Russia"],answer:3,difficulty:"easy"},
    {id:"ge25",q:"The Sahara Desert is primarily in which continent?",options:["Asia","Middle East","Africa","South America"],answer:2,difficulty:"easy"},
    {id:"ge26",q:"Which country is home to the city of Marrakech?",options:["Tunisia","Algeria","Libya","Morocco"],answer:3,difficulty:"medium"},
    {id:"ge27",q:"What is the capital of New Zealand?",options:["Auckland","Christchurch","Dunedin","Wellington"],answer:3,difficulty:"medium"},
    {id:"ge28",q:"Which country is Serengeti National Park located in?",options:["Kenya","South Africa","Botswana","Tanzania"],answer:3,difficulty:"medium"},
    {id:"ge29",q:"What is the capital of Egypt?",options:["Alexandria","Luxor","Giza","Cairo"],answer:3,difficulty:"easy"},
    {id:"ge30",q:"Which continent has no countries?",options:["Arctic","Atlantic","Antarctica","Southern Ocean"],answer:2,difficulty:"easy"},
    {id:"ge31",q:"The Strait of Gibraltar connects which two bodies of water?",options:["Red Sea and Indian Ocean","Black Sea and Mediterranean","Atlantic Ocean and Mediterranean Sea","North Sea and Baltic Sea"],answer:2,difficulty:"medium"},
    {id:"ge32",q:"What is the longest river in Europe?",options:["Rhine","Danube","Volga","Thames"],answer:2,difficulty:"hard"},
    {id:"ge33",q:"What is the capital of Turkey?",options:["Istanbul","Izmir","Bursa","Ankara"],answer:3,difficulty:"medium"},
    {id:"ge34",q:"Which US state contains the Grand Canyon?",options:["Utah","Nevada","New Mexico","Arizona"],answer:3,difficulty:"easy"},
    {id:"ge35",q:"What is the smallest continent by land area?",options:["Antarctica","Europe","Australia","South America"],answer:2,difficulty:"easy"},
    {id:"ge36",q:"Which ocean is the smallest in the world?",options:["Southern","Arctic","Indian","Atlantic"],answer:1,difficulty:"medium"},
    {id:"ge37",q:"What is the capital of Saudi Arabia?",options:["Jeddah","Mecca","Medina","Riyadh"],answer:3,difficulty:"medium"},
    {id:"ge38",q:"Which country is Mount Kilimanjaro located in?",options:["Kenya","Uganda","Rwanda","Tanzania"],answer:3,difficulty:"medium"},
    {id:"ge39",q:"What is the second most spoken language in the world by native speakers?",options:["English","Hindi","Spanish","Mandarin"],answer:2,difficulty:"medium"},
    {id:"ge40",q:"Which city is known as the City of Canals?",options:["Amsterdam","Stockholm","Venice","Bangkok"],answer:2,difficulty:"easy"},
    {id:"ge41",q:"What is the capital of India?",options:["Mumbai","Kolkata","Chennai","New Delhi"],answer:3,difficulty:"easy"},
    {id:"ge42",q:"Which country are the Galapagos Islands part of?",options:["Peru","Colombia","Chile","Ecuador"],answer:3,difficulty:"medium"},
    {id:"ge43",q:"What is the name of the sea between Italy and Croatia?",options:["Ligurian Sea","Tyrrhenian Sea","Adriatic Sea","Ionian Sea"],answer:2,difficulty:"medium"},
    {id:"ge44",q:"Which country is home to the ruins of Petra?",options:["Israel","Syria","Lebanon","Jordan"],answer:3,difficulty:"medium"},
    {id:"ge45",q:"The Gobi Desert spans which two countries?",options:["Iran and Afghanistan","Kazakhstan and Russia","China and Mongolia","India and Pakistan"],answer:2,difficulty:"medium"},
    {id:"ge46",q:"What is the capital of Nigeria?",options:["Lagos","Ibadan","Kano","Abuja"],answer:3,difficulty:"medium"},
    {id:"ge47",q:"Which US state is home to Yellowstone National Park?",options:["Montana","Idaho","Colorado","Wyoming"],answer:3,difficulty:"medium"},
    {id:"ge48",q:"What is the largest lake in Africa?",options:["Lake Tanganyika","Lake Malawi","Lake Victoria","Lake Chad"],answer:2,difficulty:"medium"},
    {id:"ge49",q:"Which country has the most UNESCO World Heritage Sites?",options:["France","China","Italy","Spain"],answer:2,difficulty:"hard"},
    {id:"ge50",q:"What is the deepest lake in the world?",options:["Lake Superior","Lake Titicaca","Lake Tanganyika","Lake Baikal"],answer:3,difficulty:"medium"},
  ],
  "Food & Drink": [
    {id:"fd1",q:"Which country is credited with inventing champagne?",options:["Italy","France","Spain","Germany"],answer:1,difficulty:"medium"},
    {id:"fd2",q:"What is the main ingredient in guacamole?",options:["Tomato","Onion","Avocado","Lime"],answer:2,difficulty:"easy"},
    {id:"fd3",q:"Sushi originated in which country?",options:["China","Korea","Japan","Thailand"],answer:2,difficulty:"easy"},
    {id:"fd4",q:"What type of pasta is shaped like little rice grains?",options:["Orzo","Farfalle","Conchiglie","Stelline"],answer:0,difficulty:"medium"},
    {id:"fd5",q:"What is the worlds most expensive spice by weight?",options:["Vanilla","Cardamom","Saffron","Truffle"],answer:2,difficulty:"medium"},
    {id:"fd6",q:"Which fruit is known as the king of fruits in Southeast Asia?",options:["Mango","Durian","Rambutan","Jackfruit"],answer:1,difficulty:"medium"},
    {id:"fd7",q:"What is the base spirit in a traditional Margarita?",options:["Rum","Vodka","Gin","Tequila"],answer:3,difficulty:"easy"},
    {id:"fd8",q:"Brie and Camembert cheeses originate from which country?",options:["Italy","Switzerland","France","Netherlands"],answer:2,difficulty:"easy"},
    {id:"fd9",q:"What compound makes chili peppers spicy?",options:["Piperine","Gingerol","Capsaicin","Allicin"],answer:2,difficulty:"hard"},
    {id:"fd10",q:"Which city is famous for originating deep-dish pizza?",options:["New York","Chicago","Detroit","Philadelphia"],answer:1,difficulty:"easy"},
    {id:"fd11",q:"What is the Japanese fermented soybean paste used in soups?",options:["Tofu","Miso","Dashi","Umami"],answer:1,difficulty:"medium"},
    {id:"fd12",q:"How many fluid ounces are in a standard US pint?",options:["12","14","16","20"],answer:2,difficulty:"medium"},
    {id:"fd13",q:"What country produces the most coffee in the world?",options:["Colombia","Ethiopia","Vietnam","Brazil"],answer:3,difficulty:"medium"},
    {id:"fd14",q:"What is the traditional main ingredient in French bouillabaisse?",options:["Chicken","Beef","Seafood","Vegetables"],answer:2,difficulty:"hard"},
    {id:"fd15",q:"What is the main ingredient in hummus?",options:["Lentils","Chickpeas","White Beans","Fava Beans"],answer:1,difficulty:"easy"},
    {id:"fd16",q:"Which country invented croissants?",options:["France","Austria","Switzerland","Belgium"],answer:1,difficulty:"hard"},
    {id:"fd17",q:"What type of wine is Merlot?",options:["Sparkling","White","Rose","Red"],answer:3,difficulty:"easy"},
    {id:"fd18",q:"What is the most consumed beverage in the world after water?",options:["Coffee","Beer","Tea","Orange Juice"],answer:2,difficulty:"medium"},
    {id:"fd19",q:"What nut is used to make marzipan?",options:["Cashew","Walnut","Hazelnut","Almond"],answer:3,difficulty:"medium"},
    {id:"fd20",q:"What is tofu made from?",options:["Rice","Chickpeas","Soybeans","Almonds"],answer:2,difficulty:"easy"},
    {id:"fd21",q:"How many calories are in a gram of pure fat?",options:["4","7","9","12"],answer:2,difficulty:"hard"},
    {id:"fd22",q:"What is Italian tiramisu traditionally made with?",options:["Cream cheese","Ricotta","Mascarpone","Brie"],answer:2,difficulty:"medium"},
    {id:"fd23",q:"Which grain is used to make most bourbon whiskey?",options:["Wheat","Barley","Rye","Corn"],answer:3,difficulty:"medium"},
    {id:"fd24",q:"What is the main flavoring in a traditional mojito?",options:["Basil","Cilantro","Mint","Parsley"],answer:2,difficulty:"easy"},
    {id:"fd25",q:"What is the French term for a thin pancake?",options:["Galette","Eclair","Crepe","Mille-feuille"],answer:2,difficulty:"easy"},
    {id:"fd26",q:"What ingredient gives bread its rise?",options:["Baking soda","Yeast","Salt","Sugar"],answer:1,difficulty:"easy"},
    {id:"fd27",q:"Which country produces the most olive oil in the world?",options:["Greece","Italy","Tunisia","Spain"],answer:3,difficulty:"medium"},
    {id:"fd28",q:"What is the name of the Italian rice dish cooked with broth?",options:["Polenta","Farro","Risotto","Orzo"],answer:2,difficulty:"easy"},
    {id:"fd29",q:"What is naan?",options:["Indian rice","Indian flatbread","Indian curry","Indian pickle"],answer:1,difficulty:"easy"},
    {id:"fd30",q:"What spirit is used in a classic Negroni cocktail?",options:["Vodka","Rum","Tequila","Gin"],answer:3,difficulty:"medium"},
    {id:"fd31",q:"What is the primary ingredient in the Spanish dish gazpacho?",options:["Cucumber","Peppers","Tomato","Onion"],answer:2,difficulty:"medium"},
    {id:"fd32",q:"Which country is most associated with the origin of chocolate?",options:["Switzerland","Belgium","Mexico","Ghana"],answer:2,difficulty:"medium"},
    {id:"fd33",q:"What pasta shape is used in a traditional carbonara?",options:["Penne","Fettuccine","Rigatoni","Spaghetti"],answer:3,difficulty:"medium"},
    {id:"fd34",q:"What is the most popular pizza topping in America?",options:["Mushrooms","Sausage","Pepperoni","Extra Cheese"],answer:2,difficulty:"easy"},
    {id:"fd35",q:"What is sake made from?",options:["Barley","Wheat","Rice","Potato"],answer:2,difficulty:"medium"},
    {id:"fd36",q:"What is the key difference between jam and jelly?",options:["Sugar content","Fruit content","Jam has fruit chunks jelly is clear","Cooking method"],answer:2,difficulty:"easy"},
    {id:"fd37",q:"Which country is famous for poutine?",options:["United States","Belgium","Canada","France"],answer:2,difficulty:"easy"},
    {id:"fd38",q:"What type of cheese is traditionally used in a Greek salad?",options:["Gouda","Haloumi","Brie","Feta"],answer:3,difficulty:"easy"},
    {id:"fd39",q:"What is Worcestershire sauce primarily made from?",options:["Tomatoes","Anchovies","Mushrooms","Vinegar"],answer:1,difficulty:"hard"},
    {id:"fd40",q:"Which country is the leading producer of wine?",options:["France","Argentina","Italy","Spain"],answer:2,difficulty:"medium"},
    {id:"fd41",q:"What is the popular Korean spicy fermented cabbage called?",options:["Gochujang","Miso","Kimchi","Doenjang"],answer:2,difficulty:"easy"},
    {id:"fd42",q:"What is a degustation menu?",options:["A vegan menu","A prix fixe brunch","A multi-course tasting menu","A childrens menu"],answer:2,difficulty:"hard"},
    {id:"fd43",q:"Which country invented beer according to ancient history?",options:["Germany","England","Egypt","Mesopotamia"],answer:3,difficulty:"hard"},
    {id:"fd44",q:"What is the national dish of England?",options:["Fish and Chips","Roast Beef","Chicken Tikka Masala","Shepherds Pie"],answer:2,difficulty:"hard"},
    {id:"fd45",q:"What is the main grain in a traditional Italian polenta?",options:["Wheat","Oat","Barley","Corn"],answer:3,difficulty:"medium"},
    {id:"fd46",q:"What is the primary flavoring agent in a classic Caesar cocktail?",options:["Tomato juice","Clamato juice","Clam juice","Worcestershire"],answer:1,difficulty:"hard"},
    {id:"fd47",q:"Which fruit was originally called a love apple in Europe?",options:["Strawberry","Pineapple","Tomato","Pomegranate"],answer:2,difficulty:"medium"},
    {id:"fd48",q:"What is the primary souring ingredient in traditional Thai pad thai?",options:["Tamarind","Lime","Mango","Pineapple"],answer:0,difficulty:"hard"},
    {id:"fd49",q:"How many tea varieties come from the same plant Camellia sinensis?",options:["2","4","6","8"],answer:2,difficulty:"hard"},
    {id:"fd50",q:"What spirit is the base of a classic gin and tonic?",options:["Vodka","Rum","Gin","Whiskey"],answer:2,difficulty:"easy"},
  ],
  Music: [
    {id:"mu1",q:"Which band released the album Abbey Road in 1969?",options:["The Rolling Stones","The Who","The Beatles","Led Zeppelin"],answer:2,difficulty:"easy"},
    {id:"mu2",q:"What is the best-selling album of all time?",options:["Back in Black","Rumours","Thriller","The Dark Side of the Moon"],answer:2,difficulty:"medium"},
    {id:"mu3",q:"Which artist is known as the Queen of Pop?",options:["Whitney Houston","Beyonce","Madonna","Mariah Carey"],answer:2,difficulty:"easy"},
    {id:"mu4",q:"How many strings does a standard guitar have?",options:["4","5","6","7"],answer:2,difficulty:"easy"},
    {id:"mu5",q:"Which composer wrote the Moonlight Sonata?",options:["Mozart","Bach","Chopin","Beethoven"],answer:3,difficulty:"medium"},
    {id:"mu6",q:"What genre of music originated in Kingston Jamaica?",options:["Calypso","Ska","Reggae","Dancehall"],answer:2,difficulty:"medium"},
    {id:"mu7",q:"Which artist has won the most Grammy Awards of all time?",options:["Beyonce","Georg Solti","Quincy Jones","Jay-Z"],answer:0,difficulty:"hard"},
    {id:"mu8",q:"In music what does forte mean?",options:["Slow","Loud","Soft","Fast"],answer:1,difficulty:"medium"},
    {id:"mu9",q:"Which rock band is known as The Fab Four?",options:["The Rolling Stones","The Doors","The Beatles","The Who"],answer:2,difficulty:"easy"},
    {id:"mu10",q:"What instrument does a luthier make and repair?",options:["Brass instruments","Drums","String instruments","Woodwinds"],answer:2,difficulty:"hard"},
    {id:"mu11",q:"Which decade did hip-hop music emerge from New York City?",options:["1960s","1970s","1980s","1990s"],answer:1,difficulty:"medium"},
    {id:"mu12",q:"Who wrote the opera The Marriage of Figaro?",options:["Verdi","Puccini","Mozart","Wagner"],answer:2,difficulty:"hard"},
    {id:"mu13",q:"What is the lowest-pitched brass instrument?",options:["Trombone","French Horn","Euphonium","Tuba"],answer:3,difficulty:"medium"},
    {id:"mu14",q:"Which artist released the album Nevermind in 1991?",options:["Pearl Jam","Soundgarden","Nirvana","Alice in Chains"],answer:2,difficulty:"easy"},
    {id:"mu15",q:"What does BPM stand for in music?",options:["Bass Per Minute","Beats Per Measure","Beats Per Minute","Base Performance Meter"],answer:2,difficulty:"easy"},
    {id:"mu16",q:"How many keys are on a standard piano?",options:["76","82","88","96"],answer:2,difficulty:"medium"},
    {id:"mu17",q:"Which band is known for the concept album The Wall?",options:["Led Zeppelin","The Who","Pink Floyd","Genesis"],answer:2,difficulty:"medium"},
    {id:"mu18",q:"Which singer is known as the King of Soul?",options:["James Brown","Sam Cooke","Otis Redding","Ray Charles"],answer:1,difficulty:"medium"},
    {id:"mu19",q:"What country did ABBA originate from?",options:["Denmark","Norway","Finland","Sweden"],answer:3,difficulty:"easy"},
    {id:"mu20",q:"Which composer wrote The Four Seasons?",options:["Bach","Handel","Vivaldi","Pachelbel"],answer:2,difficulty:"medium"},
    {id:"mu21",q:"What does a cappella mean?",options:["With instruments","Voice only without instruments","Softly","Quickly"],answer:1,difficulty:"medium"},
    {id:"mu22",q:"Which band had the hit Smells Like Teen Spirit?",options:["Pearl Jam","Foo Fighters","Nirvana","Soundgarden"],answer:2,difficulty:"easy"},
    {id:"mu23",q:"Who is considered the King of Blues?",options:["Muddy Waters","Robert Johnson","B.B. King","John Lee Hooker"],answer:2,difficulty:"medium"},
    {id:"mu24",q:"In music theory how many semitones are in an octave?",options:["8","10","12","14"],answer:2,difficulty:"hard"},
    {id:"mu25",q:"Which artists real name is Stefani Germanotta?",options:["Beyonce","Rihanna","Lady Gaga","Katy Perry"],answer:2,difficulty:"easy"},
    {id:"mu26",q:"Which classical composer was deaf when he wrote his 9th Symphony?",options:["Mozart","Schubert","Beethoven","Brahms"],answer:2,difficulty:"easy"},
    {id:"mu27",q:"What instrument is Yo-Yo Ma famous for playing?",options:["Violin","Viola","Cello","Double Bass"],answer:2,difficulty:"medium"},
    {id:"mu28",q:"Which music genre originated in New Orleans in the early 20th century?",options:["Blues","Soul","Jazz","Funk"],answer:2,difficulty:"easy"},
    {id:"mu29",q:"What is the Italian term for gradually getting louder?",options:["Decrescendo","Diminuendo","Crescendo","Fortissimo"],answer:2,difficulty:"medium"},
    {id:"mu30",q:"Which album contains the track Bohemian Rhapsody?",options:["Sheer Heart Attack","Jazz","A Night at the Opera","News of the World"],answer:2,difficulty:"medium"},
    {id:"mu31",q:"How many strings does a violin have?",options:["3","4","5","6"],answer:1,difficulty:"easy"},
    {id:"mu32",q:"Which country has won the Eurovision Song Contest the most times?",options:["Sweden","United Kingdom","France","Ireland"],answer:3,difficulty:"hard"},
    {id:"mu33",q:"Who wrote the song Yesterday recorded by The Beatles?",options:["George Harrison","Ringo Starr","John Lennon","Paul McCartney"],answer:3,difficulty:"medium"},
    {id:"mu34",q:"Which artist had a famous Eras Tour in 2023 and 2024?",options:["Beyonce","Taylor Swift","Billie Eilish","Olivia Rodrigo"],answer:1,difficulty:"easy"},
    {id:"mu35",q:"Who wrote The Nutcracker ballet?",options:["Stravinsky","Dvorak","Prokofiev","Tchaikovsky"],answer:3,difficulty:"medium"},
    {id:"mu36",q:"What does the musical term allegro mean?",options:["Slow","Very Slow","Fast and Lively","Very Loud"],answer:2,difficulty:"medium"},
    {id:"mu37",q:"Which American city is considered the birthplace of country music?",options:["Austin","Memphis","Nashville","Atlanta"],answer:2,difficulty:"easy"},
    {id:"mu38",q:"Who sang Purple Rain?",options:["Michael Jackson","James Brown","Prince","David Bowie"],answer:2,difficulty:"easy"},
    {id:"mu39",q:"Which band released Back in Black in 1980?",options:["Led Zeppelin","Aerosmith","AC/DC","Black Sabbath"],answer:2,difficulty:"medium"},
    {id:"mu40",q:"Who is known as the Godfather of Punk?",options:["Joey Ramone","Sid Vicious","Iggy Pop","Johnny Rotten"],answer:2,difficulty:"hard"},
    {id:"mu41",q:"Which band is Stairway to Heaven associated with?",options:["Deep Purple","Black Sabbath","Led Zeppelin","The Doors"],answer:2,difficulty:"easy"},
    {id:"mu42",q:"What is the name of the scale that uses all 12 notes equally?",options:["Major Scale","Minor Scale","Pentatonic Scale","Chromatic Scale"],answer:3,difficulty:"hard"},
    {id:"mu43",q:"In what year was Spotify founded?",options:["2004","2006","2008","2010"],answer:1,difficulty:"hard"},
    {id:"mu44",q:"What is the name of the standard tuning note orchestras use?",options:["C4","G4","A4","E4"],answer:2,difficulty:"hard"},
    {id:"mu45",q:"What music format succeeded the cassette tape commercially?",options:["8-Track","Minidisc","CD","DAT"],answer:2,difficulty:"easy"},
    {id:"mu46",q:"Which singer is known for the albums Lemonade and Renaissance?",options:["Rihanna","Adele","Beyonce","Alicia Keys"],answer:2,difficulty:"easy"},
    {id:"mu47",q:"Which legendary guitarist was known as Slowhand?",options:["Jimi Hendrix","Eric Clapton","Carlos Santana","Jeff Beck"],answer:1,difficulty:"medium"},
    {id:"mu48",q:"What is the name of the musical term for how loud or soft to play?",options:["Tempo","Dynamics","Rhythm","Timbre"],answer:1,difficulty:"medium"},
    {id:"mu49",q:"Which band recorded the album Dark Side of the Moon?",options:["Genesis","Yes","Pink Floyd","Emerson Lake and Palmer"],answer:2,difficulty:"easy"},
    {id:"mu50",q:"What instrument uses a bow and has four strings tuned in fifths?",options:["Guitar","Mandolin","Violin","Ukulele"],answer:2,difficulty:"easy"},
  ],
  Oddities: [
    {id:"od1",q:"In what year was Silly Putty invented?",options:["1939","1943","1950","1957"],answer:1,difficulty:"hard"},
    {id:"od2",q:"What color is a polar bears skin underneath its white fur?",options:["Pink","White","Grey","Black"],answer:3,difficulty:"medium"},
    {id:"od3",q:"How many hearts does an octopus have?",options:["1","2","3","4"],answer:2,difficulty:"medium"},
    {id:"od4",q:"What is the only fruit with seeds on the outside?",options:["Raspberry","Strawberry","Blackberry","Kiwi"],answer:1,difficulty:"medium"},
    {id:"od5",q:"A group of flamingos is called a what?",options:["Flock","Flamboyance","Colony","Gaggle"],answer:1,difficulty:"hard"},
    {id:"od6",q:"Which US president appeared on the TV show Laugh-In?",options:["LBJ","Gerald Ford","Richard Nixon","Jimmy Carter"],answer:2,difficulty:"hard"},
    {id:"od7",q:"What was the first toy advertised on US television?",options:["Barbie","Mr. Potato Head","Slinky","Hula Hoop"],answer:1,difficulty:"hard"},
    {id:"od8",q:"How many sides does a snowflake have?",options:["4","5","6","8"],answer:2,difficulty:"medium"},
    {id:"od9",q:"Which animal cannot stick out its tongue?",options:["Dolphin","Turtle","Crocodile","Elephant"],answer:2,difficulty:"hard"},
    {id:"od10",q:"What is the dot above the letter i called?",options:["A serif","A tittle","A pip","A dot"],answer:1,difficulty:"hard"},
    {id:"od11",q:"How long is a goldfish memory according to popular belief?",options:["2 seconds","3 seconds","5 seconds","10 seconds"],answer:1,difficulty:"easy"},
    {id:"od12",q:"How many dimples does a regulation golf ball have?",options:["226","336","420","500"],answer:1,difficulty:"hard"},
    {id:"od13",q:"What percentage of the human body is water approximately?",options:["45%","55%","60%","75%"],answer:2,difficulty:"medium"},
    {id:"od14",q:"A snail can sleep for how long?",options:["1 week","1 month","3 years","10 years"],answer:2,difficulty:"hard"},
    {id:"od15",q:"What is the most common street name in the United States?",options:["Main Street","Oak Street","Park Avenue","Second Street"],answer:3,difficulty:"hard"},
    {id:"od16",q:"How many teeth does an adult human have?",options:["28","30","32","34"],answer:2,difficulty:"easy"},
    {id:"od17",q:"What color is a giraffe tongue?",options:["Pink","Red","Purple","Blue-Black"],answer:3,difficulty:"medium"},
    {id:"od18",q:"What is the collective noun for a group of crows?",options:["Pack","Murder","Flock","Gaggle"],answer:1,difficulty:"medium"},
    {id:"od19",q:"How many arms does a starfish typically have?",options:["4","5","6","8"],answer:1,difficulty:"easy"},
    {id:"od20",q:"Which fruit was originally called a love apple in Europe?",options:["Strawberry","Pineapple","Tomato","Pomegranate"],answer:2,difficulty:"medium"},
    {id:"od21",q:"How many taste buds does the average human tongue have?",options:["1000","5000","10000","50000"],answer:2,difficulty:"medium"},
    {id:"od22",q:"Which country has the highest number of vending machines per capita?",options:["South Korea","United States","Germany","Japan"],answer:3,difficulty:"medium"},
    {id:"od23",q:"What is the technical term for an ice cream headache?",options:["Sphenopalatine ganglioneuralgia","Trigeminal neuralgia","Occipital neuralgia","Temporal neuralgia"],answer:0,difficulty:"hard"},
    {id:"od24",q:"What is the national animal of Scotland?",options:["Red Deer","Golden Eagle","Unicorn","Red Lion"],answer:2,difficulty:"medium"},
    {id:"od25",q:"What is the only letter that does not appear in any US state name?",options:["Q","X","Z","B"],answer:0,difficulty:"hard"},
    {id:"od26",q:"Which country invented the modern flush toilet?",options:["France","Germany","England","United States"],answer:2,difficulty:"medium"},
    {id:"od27",q:"How many muscles does the human face have?",options:["20","43","66","100"],answer:1,difficulty:"medium"},
    {id:"od28",q:"What is the shortest war in history?",options:["Six-Day War","Gulf War","Anglo-Zanzibar War","Falklands War"],answer:2,difficulty:"hard"},
    {id:"od29",q:"How many noses does a slug have?",options:["1","2","4","6"],answer:2,difficulty:"hard"},
    {id:"od30",q:"What is a jiffy as an actual unit of time?",options:["1/10 of a second","1/100 of a second","1/1000 of a second","0.01 nanoseconds"],answer:1,difficulty:"hard"},
    {id:"od31",q:"Which planet smells like rotten eggs due to hydrogen sulfide?",options:["Mars","Neptune","Uranus","Saturn"],answer:2,difficulty:"hard"},
    {id:"od32",q:"How many muscles does a caterpillar have?",options:["100","400","4000","10000"],answer:2,difficulty:"hard"},
    {id:"od33",q:"How many bubbles are in a standard glass of champagne approximately?",options:["100000","500000","49 million","250 million"],answer:2,difficulty:"hard"},
    {id:"od34",q:"How many eyelids does a camel have?",options:["1","2","3","4"],answer:2,difficulty:"medium"},
    {id:"od35",q:"Which country has the most tornadoes per year?",options:["Australia","Bangladesh","Canada","United States"],answer:3,difficulty:"medium"},
    {id:"od36",q:"How long does it take for fingernails to grow 1 inch?",options:["3 months","6 months","12 months","18 months"],answer:1,difficulty:"medium"},
    {id:"od37",q:"What is the name of the worlds oldest known living tree?",options:["Old Tjikko","Methuselah","Prometheus","Pando"],answer:1,difficulty:"hard"},
    {id:"od38",q:"A group of porcupines is called a what?",options:["Pack","Prickle","Cluster","Posse"],answer:1,difficulty:"hard"},
    {id:"od39",q:"What is the speed of a sneeze in mph approximately?",options:["30 mph","100 mph","500 mph","200 mph"],answer:1,difficulty:"hard"},
    {id:"od40",q:"How many languages are spoken in Papua New Guinea approximately?",options:["50","200","500","800"],answer:3,difficulty:"hard"},
    {id:"od41",q:"What is the most common eye color in the world?",options:["Blue","Green","Hazel","Brown"],answer:3,difficulty:"easy"},
    {id:"od42",q:"Which animal has the highest blood pressure?",options:["Elephant","Blue Whale","Horse","Giraffe"],answer:3,difficulty:"medium"},
    {id:"od43",q:"What color was Coca-Colas original logo?",options:["Red","Blue","Black","Green"],answer:2,difficulty:"hard"},
    {id:"od44",q:"How far can a skunks spray reach?",options:["3 feet","6 feet","10 feet","25 feet"],answer:3,difficulty:"medium"},
    {id:"od45",q:"How many hearts does an earthworm have?",options:["1","3","5","10"],answer:2,difficulty:"hard"},
    {id:"od46",q:"What is the longest English word with no repeated letters?",options:["Uncopyrightable","Dermatoglyphics","Troublemakings","Subdermatoglyphic"],answer:3,difficulty:"hard"},
    {id:"od47",q:"What is the name of the phobia of being stared at?",options:["Scopophobia","Ophthalmophobia","Scoptophobia","All of the above"],answer:3,difficulty:"hard"},
    {id:"od48",q:"How many pounds of oxygen does the average human breathe per day?",options:["0.5 lbs","1.5 lbs","2 lbs","3 lbs"],answer:1,difficulty:"hard"},
    {id:"od49",q:"Which country has won the most Nobel Prizes per capita?",options:["United States","Switzerland","Sweden","Faroe Islands"],answer:2,difficulty:"hard"},
    {id:"od50",q:"What is the approximate weight of an average cumulus cloud?",options:["500 tons","100000 lbs","1.1 million pounds","1000 lbs"],answer:2,difficulty:"hard"},
  ],
};